name: litte

on:
  push:
    paths:
      - '.github/workflows/litte.yml'
      - 'commit/**'
  schedule:
    - cron: 0 */6 * * *
  repository_dispatch:
    workflow_dispatch:
      inputs:
        packages:
          description: 'packages'
          required: false
          default: 'false'	

jobs:
  job_litte:
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id
    runs-on: ubuntu-latest

    name: Update litte

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Initialization environment
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Clone packages
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x .github/diy/${{matrix.target}}.sh
        git clone -b master https://github.com/kenzok8/litte.git ${{matrix.target}}
        cd ${{matrix.target}}
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "commit"` >/dev/null 2>&1     
        $GITHUB_WORKSPACE/.github/diy/${{matrix.target}}.sh
        bash /$GITHUB_WORKSPACE/.github/diy/convert_translation.sh
        bash /$GITHUB_WORKSPACE/.github/diy/create_acl_for_luci.sh -a
        bash /$GITHUB_WORKSPACE/.github/diy/Modify.sh

    - name: Extract PLUGIN_VERSION
      run: |
        PLUGIN_VERSIONS=()
        for file in $(find . -type f -name Makefile); do
          version=$(grep -E 'PKG_(BASE_)?VERSION\s*?:=' $file | awk -F '[:=]' '{print $2}')
          if [ -n "$version" ]; then
            PLUGIN_NAME=$(basename $(dirname $file))
            PLUGIN_VERSIONS+=("$PLUGIN_NAME: update to $version")
          fi
        done

        # Combine versions into a single string
        PLUGIN_VERSION="${PLUGIN_VERSIONS[*]}"
        echo "PLUGIN_VERSION=$PLUGIN_VERSION" >> $GITHUB_ENV

    - name: Debug PLUGIN_VERSION
      run: echo "PLUGIN_VERSION is $PLUGIN_VERSION"

    - name: Create commitmessage.txt
      run: echo "$PLUGIN_VERSION" > commitmessage.txt

    - name: Set commit message
      id: commit_message_step
      run: |
        echo 'commit_message<<EOF' >> $GITHUB_ENV
        cat commitmessage.txt >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Debug Commit Message
      run: echo "Commit Message is ${{ steps.commit_message_step.outputs.commit_message }}"

    - name: Commit and Push
      run: |
        cd $GITHUB_WORKSPACE/${{matrix.target}}
        git add .
        git commit -m "${{ steps.commit_message_step.outputs.commit_message }}"
        git push "https://${{ secrets.ACCESS_TOKEN }}@github.com/kenzok8/litte.git" HEAD:${{matrix.target}}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1
